DEBUG:root:Updated usage count for Stack Overflow to 1
DEBUG:root:Updated usage count for Python Docs to 1
DEBUG:root:Updated usage count for Stack Overflow to 2
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): stackoverflow.com:443
DEBUG:urllib3.connectionpool:https://stackoverflow.com:443 "GET / HTTP/11" 200 None
DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): cdn.sstatic.net:443
DEBUG:urllib3.connectionpool:https://cdn.sstatic.net:443 "GET /Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded HTTP/11" 200 6562
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:urllib3.connectionpool:https://github.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.githubassets.com:443
DEBUG:urllib3.connectionpool:https://github.githubassets.com:443 "GET /assets/home24-5939032587c9.jpg HTTP/11" 200 48545
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:root:Updated usage count for GitHub Repository to 1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.python.org:443
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET / HTTP/11" 302 138
DEBUG:urllib3.connectionpool:https://docs.python.org:443 "GET /3/ HTTP/11" 200 3568
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET / HTTP/11" 200 None
DEBUG:root:Updated usage count for Google to 2
